version: "3.7"
networks:
  data_analytic:
    external: true

x-network-common: &network-common
  networks:
    - data_analytic

services:
  da-traefik:
    image: traefik:latest
    <<: *network-common
    hostname: traefik
    environment:
      - TZ=Asia/Bangkok
    ports:
      # - 80:80 # entrypoint: web (redriect schema to (https: 443: websecure))
      - 30443:443 # entrypoint: websecure (n8n service --> /n8n) && (minio-console --> /)
      - 38080:8080 # entrypoint: dashboard
      - 39000:9000 # entrypoint: minio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/:/traefic/configs
      - ./certs/:/certs
      - ./logs/traefik/:/var/log/traefik/
    restart: unless-stopped

    command:
      # Expose Endport listener
      # - "--entrypoints.web.address=:80"
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.dashboard.address=:8080"
      - "--entrypoints.minio.address=:9000"

      - "--global.sendAnonymousUsage"
      # - "--global.checkNewVersion"
      - "--serverstransport.insecureskipverify=true"
      # Operations
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--ping"
      - "--ping.manualrouting=true"

      # Provider
      - "--providers.docker"
      - "--providers.docker.swarmmode=false" # true if use docker swarm mode
      - "--providers.docker.network=data_analytic" # set network name
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.httpclienttimeout=3600"
      - "--providers.file.directory=/traefic/configs"
      - "--providers.file.watch=true"

      # logs
      - "--log.level=INFO"
      - "--accesslog"
      - "--accesslog.bufferingsize=100"
      - "--accesslog.filepath=/var/log/traefik/access.log"

    labels:
      - "traefik.enable=true"

  da-traefik-logrotate:
    image: vegardit/traefik-logrotate:latest
    <<: *network-common
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw # required to send USR1 signal to Traefik after log rotation
      - ./logs/traefik:/var/log/traefik:rw # folder containing access.log file
    environment:
      TZ: "Asia/Bangkok"
      # all environment variables are optional and show the default values:
      LOGROTATE_LOGS: "/var/log/traefik/*.log" # log files to rotate, directory must match volume mount
      LOGROTATE_TRIGGER_INTERVAL: daily # rotate daily, must be one of: daily, weekly, monthly, yearly
      LOGROTATE_TRIGGER_SIZE: 100M # rotate if log file size reaches 50MB
      LOGROTATE_MAX_BACKUPS: 90 # keep 14 backup copies per rotated log file
      LOGROTATE_START_INDEX: 1 # first rotated file is called access.1.log
      CRON_SCHEDULE: "* * * * *"
      CRON_LOG_LEVEL: 8 # see https://unix.stackexchange.com/a/414010/378036
      # command to determine the id of the container running Traefik:
      TRAEFIK_CONTAINER_ID_COMMAND: docker ps --quiet --filter ancestor=da-traefik
