version: "3.7"

networks:
  data_analytic:
    external: true
  minio:

x-network-common: &network-common
  networks:
    - data_analytic
    - minio
  hostname: minio
  # ports:
  #   - "9000:9000" # open api only
  #   - "9001:9001" # console port (use in traefik: https://<domain>:<port>/)

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9001" http://minio1/data{1...2} #
  # command: server --console-address ":9001" http://minio{1...2}/data{1...2} #
  restart: always
  environment:
    TZ: Asia/Bangkok
    MINIO_ROOT_USER: admin
    MINIO_ROOT_PASSWORD: admin@admin
    MINIO_BROWSER_REDIRECT_URL: https://localhost:30443
    MINIO_SERVER_URL: http://localhost:39000
    MINIO_WORM: 0
  expose:
    - "9000"
    - "9001"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
  networks:
    - minio

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  da-minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./storage/minio/data1-1:/data1
      - ./storage/minio/data1-2:/data2

  ## ---
  ##  if add more minio please add host in `./configs/minio/nginx.conf`
  ## ----
  # da-minio2:
  #   <<: *minio-common
  #   hostname: minio2
  #   volumes:
  #     - data2-1:/data1
  #     - data2-2:/data2

  # da-minio3:
  #   <<: *minio-common
  #   hostname: minio3
  #   volumes:
  #     - data3-1:/data1
  #     - data3-2:/data2

  # da-minio4:
  #   <<: *minio-common
  #   hostname: minio4
  #   volumes:
  #     - data4-1:/data1
  #     - data4-2:/data2

  nginx-minio:
    image: nginx:1.19.2-alpine
    restart: always
    volumes:
      - ./configs/minio/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - da-minio1
      # - minio2
      # - minio3
      # - minio4
    <<: *network-common
