http:
  routers:
    n8n:
      rule: Host(`localhost`) && PathPrefix(`/n8n{regex:$$|/.*}`)
      # rule: Host(`localhost`) && PathPrefix(`/n8n{regex:$$|/.*}`)
      service: n8n
      middlewares:
        - n8n-stripprefix
        - n8n
      entryPoints:
        - websecure
      tls: true

  middlewares:
    n8n-stripprefix:
      stripprefix:
        prefixes: /n8n
    n8n:
      headers:
        SSLRedirect: false
        STSSeconds: 315360000
        browserXSSFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        SSLHost: localhost
        STSIncludeSubdomains: true
        STSPreload: true

  services:
    n8n:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"
